set -x
SITEID='KUMC'
sqlplus $USER_NAME/$USER_PASSWORD@$ORACLE_SID @covid_clinical_course.sql
sqlplus $USER_NAME/$USER_PASSWORD@$ORACLE_SID @covid_daily_counts.sql
sqlplus $USER_NAME/$USER_PASSWORD@$ORACLE_SID @covid_demographics.sql
sqlplus $USER_NAME/$USER_PASSWORD@$ORACLE_SID @covid_diagnoses.sql
sqlplus $USER_NAME/$USER_PASSWORD@$ORACLE_SID @covid_labs.sql
sqlplus $USER_NAME/$USER_PASSWORD@$ORACLE_SID @covid_medications.sql


sed -i 1i"SITEID,DAYS_SINCE_ADMISSION,NUM_PATIENTS_ALL_STILL_IN_HOSPITAL,NUM_PATIENTS_EVER_SEVERE_STILL_IN_HOSPITAL" ClinicalCourse-${SITEID}.csv

sed -i 1i"SITEID,CALENDAR_DATE,CUMULATIVE_PATIENTS_ALL,CUMULATIVE_PATIENTS_SEVERE,CUMULATIVE_PATIENTS_DEAD,NUM_PATIENTS_IN_HOSPITAL_ON_THIS_DATE,NUM_PATIENTS_IN_HOSPITAL_AND_SEVERE_ON_THIS_DATE" DailyCounts-${SITEID}.csv

sed -i 1i"SITEID,SEX,AGE_GROUP,RACE,NUM_PATIENTS_ALL,NUM_PATIENTS_EVER_SEVERE" Demographics-${SITEID}.csv

sed -i 1i"SITEID,ICD_CODE_3CHARS,ICD_VERSION,NUM_PATIENTS_ALL_BEFORE_ADMISSION,NUM_PATIENTS_ALL_SINCE_ADMISSION,NUM_PATIENTS_EVER_SEVERE_BEFORE_ADMISSION,NUM_PATIENTS_EVER_SEVERE_SINCE_ADMISSION" Diagnoses-${SITEID}.csv

sed -i 1i"SITEID,LOINC,DAYS_SINCE_ADMISSION,UNITS,NUM_PATIENTS_ALL,MEAN_VALUE_ALL,STDEV_VALUE_ALL,MEAN_LOG_VALUE_ALL,STDEV_LOG_VALUE_ALL,NUM_PATIENTS_EVER_SEVERE,MEAN_VALUE_EVER_SEVERE,STDEV_VALUE_EVER_SEVERE,MEAN_LOG_VALUE_EVER_SEVERE,STDEV_LOG_VALUE_EVER_SEVERE" Labs-${SITEID}.csv

sed -i 1i"SITEID,MED_CLASS,NUM_PATIENTS_ALL_BEFORE_ADMISSION,NUM_PATIENTS_ALL_SINCE_ADMISSION,NUM_PATIENTS_EVER_SEVERE_BEFORE_ADMISSION,NUM_PATIENTS_EVER_SEVERE_SINCE_ADMISSION" Medications-${SITEID}.csv

exit 0
# code to generate sql for export and header
select table_name ,
'select '|| listagg(column_name,' || '','' || ') within group( order by column_id ) || ' from ' || table_name || ';' sql

,listagg(column_name,',') within group( order by column_id ) header
from all_tab_cols
where OWNER ='LPATEL'
    and table_name in (
    'COVID_CLINICAL_COURSE'
    ,'COVID_DAILY_COUNTS'
    ,'COVID_DEMOGRAPHICS'
    ,'COVID_DIAGNOSES'
    ,'COVID_LABS'
    ,'COVID_MEDICATIONS'
    )
group by table_name;
